name: debts
description: "Application for calculating the cost of debts"

version: 1.0.0

environment:
  sdk: ^3.2.2

# Add regular dependencies here.
dependencies:
  uuid:
  collection:
  equatable:
  copy_with_extension:

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
  build_runner:
  flutter_lints: ^2.0.0
  copy_with_extension_gen:
